parameters:
  coredns:
    helm_values: {}
  kapitan:
    compile:
      - output_path: .
        input_type: helm
        input_paths:
          - components/charts/coredns
        helm_values: ${coredns:helm_values}
        helm_params:
          release_name: ${target}
          namespace: ${target}
    dependencies:
      - type: https
        source: https://kubernetes-charts.storage.googleapis.com/coredns-1.2.0.tgz
        unpack: True
        output_path: components/charts
