apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: coredns
    chart: coredns-1.2.0
    heritage: Tiller
    k8s-app: coredns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
    release: my-target
  name: my-target-coredns
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
      - namespaces
    verbs:
      - list
      - watch
