apiVersion: v1
data:
  Corefile: ".:53 {\n    cache 30\n    errors\n    health\n    kubernetes cluster.local\n\
    \    loadbalance round_robin\n    prometheus 0.0.0.0:9153\n    proxy . /etc/resolv.conf\n\
    }"
kind: ConfigMap
metadata:
  labels:
    app: coredns
    chart: coredns-1.2.0
    heritage: Tiller
    k8s-app: coredns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
    release: my-target
  name: my-target-coredns
