apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9153'
    prometheus.io/scrape: 'true'
  labels:
    app: coredns
    chart: coredns-1.2.0
    heritage: Tiller
    k8s-app: coredns
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: CoreDNS
    release: my-target
  name: my-target-coredns
spec:
  ports:
    - port: 53
      protocol: UDP
  selector:
    app: coredns
    k8s-app: coredns
    release: my-target
  type: ClusterIP
