apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cod
  namespace: prod-sea
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: cod
    spec:
      containers:
        - args:
            - --verbose=False
          image: alledm/cod:v2.0.0
          name: cod
          volumeMounts:
            - mountPath: /tmp
              name: data
              readOnly: true
      volumes:
        - configMap:
            name: readme
          name: data
