apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sardine
  namespace: dev-sea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sardine
    spec:
      containers:
        - args:
            - --verbose=True
          image: alledm/sardine:latest
          name: sardine
          volumeMounts:
            - mountPath: /tmp
              name: data
              readOnly: true
      volumes:
        - configMap:
            name: readme
          name: data
